version: '3.1'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=topsecret
      - POSTGRES_DB=aclnode
    ports:
      - 5432:5432
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data